### ISSUE TITLE
How to run this application

### ISSUE THREAD

**Issue by AKRASH-Nadeem** [riccardoperra/codeimage#658]
Hey,

Sorry to bother you but i am getting error when i run the application using pnpm

here is how i am running it.

install packages
```bash
pnpm install
```
running in development 
```bash
pnpm dev
```

i am getting this error 
```bash
> codeimage@1.8.2 dev /home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage
> pnpm --filter=@codeimage/app dev


> @codeimage/app@1.8.2 dev /home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/apps/codeimage
> vite --host

✘ [ERROR] Failed to resolve entry for package "@codeimage/vanilla-extract". The package may have incorrect main/module/exports specified in its package.json. [plugin externalize-deps]

    ../../node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/vite@5.4.5_@types+node@20.12.7_sass@1.61.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:46574:15)
    at resolvePackageEntry (file:///home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/vite@5.4.5_@types+node@20.12.7_sass@1.61.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:46571:3)
    at tryNodeResolve (file:///home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/vite@5.4.5_@types+node@20.12.7_sass@1.61.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:46387:16)
    at resolveByViteResolver (file:///home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/vite@5.4.5_@types+node@20.12.7_sass@1.61.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:66524:20)
    at file:///home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/vite@5.4.5_@types+node@20.12.7_sass@1.61.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:66557:28
    at requestCallbacks.on-resolve (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1373:28)
    at handleRequest (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:731:17)
    at handleIncomingPacket (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:756:7)
    at Socket.readFromStdout (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:520:28)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/vite@5.4.5_@types+node@20.12.7_sass@1.61.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:66545:18)
    at handlePlugins (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:787:5)
    at /home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:2197:15
    at new Promise (<anonymous>)
    at Object.build (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:2196:25)
    at build (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:2045:51)
    at bundleConfigFile (file:///home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/vite@5.4.5_@types+node@20.12.7_sass@1.61.0_terser@5.17.1/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:66500:24)

  The plugin "externalize-deps" was triggered by this import

    vite.config.ts:1:462:
      1 │ ...tysofthint/tools/code_image/codeimage/apps/codeimage/vite.config.ts";import {vanillaExtractPlugin} from '@codeimage/vanilla-extract';
        ╵                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/apps/codeimage/vite.config.ts
error when starting dev server:
Error: Build failed with 1 error:
../../node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "@codeimage/vanilla-extract". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1650:15)
    at /home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1485:45)
    at buildResponseToResult (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1056:7)
    at /home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/node_modules/.pnpm/esbuild@0.19.8/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
/home/ak/realted_to_work/infinitysofthint/tools/code_image/codeimage/apps/codeimage:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @codeimage/app@1.8.2 dev: `vite --host`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

Can someone help me to understand it.
I am not a node developer but i have some understanding of it.
but i am unable to understand the issue.

is package vanilla-extract not stable or maintained?

**Comment by riccardoperra** [comment]
You may have to change the prisma connector for the backend but I don't know if everything works the same. Coulnd't you use my hosted version instead? 😄

**Comment by AKRASH-Nadeem** [comment]
> You may have to change the prisma connector for the backend but I don't know if everything works the same. Coulnd't you use my hosted version instead? 😄

i want to attach to my website

**Comment by riccardoperra** [comment]
I would recommend to just attach a link 😄 Consider also that self-hosting requires enabling the authentication with Auth0, so you should configure it on your own. I can't provide support for that

**Comment by AKRASH-Nadeem** [comment]
thanks for your help.
i got it from here.
i got it working with mysql so i guess i can do the rest.

**Comment by AKRASH-Nadeem** [comment]
hey,
i was wondering is there any docs about how to run it on production.
it will be useful.

**Comment by riccardoperra** [comment]
The frontend is just a csr app so after build it can be exposed in public with something like nginx. I have never used cPanel so I don’t know about the api server, which is a nodejs process
